#!/usr/bin/env bash
# Script pings an IP address passed as arg.

# Accepts a string as arg
# Displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no,

if [ "$#" -lt "1" ]
then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    ping "$1" -c 5
fi

