#!/usr/bin/env bash
# This script loops from 1 to 10 and 4 print bad luck 8 good luck else Best school

k=1
while [ $k -le 10 ]

do
	if [ $k -eq 4 ]
	then
		echo "bad luck"
	elif [ $k -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi

	k=$(( k + 1 ))
done
