#!/usr/bin/env bash
# Script print numbers from 1 to 20 and 4 China and 9 Japan 17 Italy else nothing

k=1
while [ $k -le 20 ]

do
	echo $k

	case $k in
		4) echo "bad luck from China" ;;

		9) echo "bad luck from Japan" ;;

		17) echo "bad luck from Italy" ;;

		*)
	esac

	k=$(( k + 1 ))
done
