#!/usr/bin/env bash
# nginx must be listening on all dynamic IPs on port 8080
# You cannot use apt-get remove

pkill -f apache2
chown nginx:nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
