#!/usr/bin/env bash
# SSH client configuration

Host *
       PasswordAuthentication no
IdentityFile ~/.ssh/school
SendEnv LANG IC_*
HashKnownHosts yes
GSSAPIAuthentication yes
GSSAPIDelegateCredentials no
